---
- hosts: all
  become: true
  gather_facts: true
  any_errors_fatal: true
  pre_tasks:
    - name: Pausing for 5 seconds...
      pause:
        seconds: 5

  tasks:
    - name: Pip Install Docker
      include_role:
        name: geerlingguy.pip
        public: true

    - name: Install Docker
      include_role:
        name: geerlingguy.docker
        public: true

  roles:
    - role: cloudflare-ddns
      when: cloudflare_ddns_enabled | bool

    - role: traefik
      when: traefik_enabled | bool

    - role: qbittorrentee
      when: qbittorrentee_enabled | bool

    - role: jellyfin
      when: jellyfin_enabled | bool

    - role: syncthing
      when: syncthing_enabled | bool
