---
- name: Create Wallabag Directories
  file:
    path: "{{ item }}"
    state: directory
    mode: 0644
  with_items:
    - "{{ wallabag_data_directory }}/data"
    - "{{ wallabag_data_directory }}/images"

- name: Wallabag Docker Container
  docker_container:
    name: wallabag
    image: wallabag/wallabag:latest
    pull: true
    volumes:
      - "{{ wallabag_data_directory }}/data:/var/www/wallabag/data:rw"
      - "{{ wallabag_data_directory }}/images:/var/www/wallabag/web/assets/images:rw"
    ports:
      - "{{ wallabag_port }}:80"
    env:
      SYMFONY__ENV__DOMAIN_NAME: "https://wallabag.{{ nas_domain }}"
    restart_policy: unless-stopped
    labels:
      traefik.enable: "{{ wallabag_available_externally }}"
      traefik.docker.network: "{{ traefik_docker_network }}"
      traefik.http.middlewares.wallabag-gzip.compress: true
      traefik.http.middlewares.wallabag-redir-https.redirectScheme.scheme: "https"
      traefik.http.routers.wallabag-http.entrypoints: "http"
      traefik.http.routers.wallabag-http.rule: "Host(`wallabag.{{ nas_domain }}`)"
      traefik.http.routers.wallabag-http.middlewares: "wallabag-redir-https"
      traefik.http.routers.wallabag-https.middlewares: "wallabag-gzip"
      traefik.http.routers.wallabag-https.entrypoints: "https"
      traefik.http.routers.wallabag-https.tls: true
      traefik.http.routers.wallabag-https.rule: "Host(`wallabag.{{ nas_domain }}`)"
      traefik.http.routers.wallabag-https-assets.middlewares: "wallabag-gzip"
      traefik.http.routers.wallabag-https-assets.entrypoints: "https"
      traefik.http.routers.wallabag-https-assets.tls: true
      traefik.http.services.wallabag-backend.loadbalancer.server.scheme: "http"
      traefik.http.services.wallabag-backend.loadbalancer.server.port: "80"
    networks:
      - name: "{{ traefik_docker_network }}"
