---
- name: Create Qbittorrent Directories
  file:
    path: "{{ item }}"
    state: directory
    # mode: 0755
  with_items:
    - "{{ qbittorrent_config_directory }}"
    - "{{ qbittorrent_download_directory }}"

- name: Qbittorrent Docker Container
  docker_container:
    name: qbittorrent
    image: bernylinville/qbittorrent
    pull: true
    volumes:
      - "{{ qbittorrent_config_directory }}:/config:rw"
      - "{{ qbittorrent_download_directory }}:/downloads:rw"
    ports:
      - "{{ qbittorrent_port }}:18081"
      - "{{ qbittorrent_bt_port }}:16882"
      - "{{ qbittorrent_bt_port }}:16882/udp"
    env:
      TZ: "{{ qbittorrent_timezone }}"
      PUID: "{{ qbittorrent_user_id }}"
      PGID: "{{ qbittorrent_group_id }}"
    restart_policy: unless-stopped
    labels:
      traefik.enable: "{{ qbittorrent_available_externally }}"
      traefik.http.routers.qbittorrent.rule: "Host(`{{ qbittorrent_hostname }}.{{ ansible_nas_domain }}`)"
      traefik.http.routers.qbittorrent.tls.certresolver: "letsencrypt"
      traefik.http.routers.qbittorrent.tls.domains[0].main: "{{ ansible_nas_domain }}"
      traefik.http.routers.qbittorrent.tls.domains[0].sans: "*.{{ ansible_nas_domain }}"
      traefik.http.services.qbittorrent.loadbalancer.server.port: "18081"
