version: "3"
services:
  syncthing:
    image: linuxserver/syncthing
    container_name: syncthing
    hostname: {{ syncthing_hostname }}
    environment:
      - PUID=1000
      - PGID=1000
      - TZ={{ tz }}
    volumes:
      - "{{ syncthing_config_directory }}:/config"
      - "{{ syncthing_data_directory }}:/data"
    ports:
      - 8384:8384
      - 22000:22000/tcp
      - 22000:22000/udp
      - 21027:21027/udp
    restart: unless-stopped