version: "3"
services:
  qbittorrentee:
    image: superng6/qbittorrentee:4.3.8.10
    container_name: qbittorrentee
    environment:
      - PUID=1026
      - PGID=100
      - WEBUIPORT=8081
      - TZ=Asia/Shanghai
    volumes:
      - "./config:/config"
      - "{{ qbittorrentee_download_directory }}:/downloads"
    ports:
      - 16881:16881
      - 16881:16881/udp
      - 8081:8081
    restart: unless-stopped
